# Generated by Django 4.2.7 on 2023-11-07 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracks', '0003_artist_biography_artist_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tracks.artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='Tracks.category'),
        ),
        migrations.AlterField(
            model_name='track',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='tracks'),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
