# Generated by Django 4.2.7 on 2023-11-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracks', '0005_alter_track_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='artist',
        ),
        migrations.AddField(
            model_name='track',
            name='artist',
            field=models.ManyToManyField(blank=True, null=True, to='Tracks.artist'),
        ),
    ]
