# Generated by Django 4.2.7 on 2023-11-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracks', '0008_alter_track_artist_alter_track_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='farsi_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='farsi_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='farsi_title',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='farsi_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
