# Generated by Django 4.2.7 on 2023-11-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracks', '0009_album_farsi_name_artist_farsi_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
