# Generated by Django 4.2.7 on 2023-11-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracks', '0010_track_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='file',
            new_name='quality_128',
        ),
        migrations.AddField(
            model_name='track',
            name='quality_320',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
