# Generated by Django 4.2.7 on 2023-11-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracks', '0011_rename_file_track_quality_128_track_quality_320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ManyToManyField(related_name='albums', to='Tracks.artist'),
        ),
        migrations.AlterField(
            model_name='track',
            name='category',
            field=models.ManyToManyField(related_name='tracks', to='Tracks.category'),
        ),
    ]
