# Generated by Django 4.2.7 on 2023-11-14 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracks', '0014_track_single'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='title',
        ),
    ]
